# Generated by Django 5.1.2 on 2024-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Accountno', models.IntegerField(primary_key='accountno', serialize=False)),
                ('DoB', models.DateField()),
                ('Annualincome', models.IntegerField()),
                ('Address', models.CharField(max_length=10)),
                ('Aadharno', models.IntegerField()),
            ],
        ),
    ]
